# 名字随意
name: push to my txy server
# 触发机制, 可以定时, 或其他, 具体可自行百度, 示例为main分支push时触发
on:
  push:
    branches:
      - master
# 要执行的计划
jobs:
  # 我们只有一个任务, 就是发版, publish可以自己写其它的名字
  push-to-tencent:
    # 指定环境, 即创建环境机密时, 给环境的命名. 当然如果你创建的是仓库机密, 则无需下面这行
    environment: push to my txy server
    # 指定在Ubuntu机器上运行此工作流
    runs-on: ubuntu-latest
    env:
      # 私钥
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # 用户名
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      # 主机地址
      SSH_HOST: ${{ secrets.SSH_HOST }}
      # 指纹
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOST }}
    steps:
      # 创建ssh目录, 并启动ssh代理
      - name: setup ssh
        shell: bash
        run: |
          mkdir -p $HOME/.ssh

      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.SSH_HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          user: ${{ secrets.SSH_USERNAME }} # 服务器用户名
          pass: ${{ secrets.MY_PASSWORD }} # 服务器密码
          connect_timeout: 10s
          local: '.' # 源路径（工作流）
          remote: /usr/app/backend # 目标路径（服务器）

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          username: ${{ secrets.SSH_USERNAME }} # 服务器用户名
          password: ${{ secrets.MY_PASSWORD }} # 服务器密码
          script: |
            cd /home/app/backend # 进入服务器中的端工程所在的目录
            pwd
            ls -al
            uname -a
